### ISSUE TITLE
Noise pollution removed broke in the latest update

### ISSUE THREAD

**Issue by hawkfalcon** [rkanter/PollutionSolution#1]
Great mod, thank you. Unfortunately, noise pollution is back in the latest update.

**Comment by rkanter** [comment]
Thanks.  

Are you sure?  I just tried it and everything seems to still be working correctly.  Do you have any other mods that might be interfering?  For instance, the 1.0.1 update fixed an issue where noise pollution removal wasn't working correctly when using a mod that increased the game speed faster than normal speeds.
